In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [2]:
import warnings
import pandas as pd
import numpy as np
warnings.filterwarnings(action='ignore')

In [ ]:
import pandas as pd

df = pd.read_csv("남자배구.csv", encoding='utf8')
g_num=[]
for i in range(1, len(df['경기날짜'].unique())+1):
    g_num.append([df[df['경기날짜']==df.iloc[i,1]],df.iloc[i,2]])
df['경기번호'] = np.nan
for i in range(len(df['경기날짜'].unique())):
    g_num_idx = df[(df["경기날짜"]==g_num[i][0]) & (df['팀명']==g_num[i][1])].index
    df.loc[home_idx,'경기번호']=g_num_idx
df['경기번호']=df["경기번호"].astype("int64")
df

In [10]:
경기별_수치 = df.groupby(["경기날짜", "팀명", "결과",'이름']).sum()
# 경기별_수치['경기번호'] = 경기별_수치["경기날짜"].apply(lambda x : (x//2)+1 if x%2==0 else (x//2)+1)
경기별_수치

                           경기장  득점_득점  공격종합_시도  공격종합_성공  공격종합_공격차단  공격종합_범실  \
경기날짜       팀명    결과 이름
2017-10-14 대한항공  0  가스파리니    0     26       46       24          5        5
                    곽승석      0     10       16        8          2        0
                    백광현      0      0        0        0          0        0
                    신영수      0      0        0        0          0        0
                    정지석      0      9       22        8          2        1
...                        ...    ...      ...      ...        ...      ...
2022-02-13 현대캐피탈 0  박경민      1      0        0        0          0        0
                    박상하      1      8       10        5          1        0
                    전광인      1      9       18        9          2        0
                    최민호      1      0        0        0          0        0
                    허수봉      1     18       30       16          2        2

                           공격종합_성공률  공격종합_점유율  오픈_시도  오픈_성공  ...  블로킹_유효블락  \
경기날짜       팀명    결과 이름                                       ...
2017-10-14 대한항공  0  가스파리니     52.17     41.44     13      6  ...         4
                    곽승석       50.00     14.41      7      4  ...         0
                    백광현        0.00      0.00      0      0  ...         0
                    신영수        0.00      0.00      0      0  ...         0
                    정지석       36.36     19.82      9      2  ...         2
...                             ...       ...    ...    ...  ...       ...
2022-02-13 현대캐피탈 0  박경민        0.00      0.00      0      0  ...         0
                    박상하       50.00     11.76      3      0  ...         2
                    전광인       50.00     21.18      7      4  ...         2
                    최민호        0.00      0.00      0      0  ...         0
                    허수봉       53.33     35.29      6      3  ...         2

                           블로킹_실패  블로킹_범실  블로킹_세트당  블로킹_점유율  블로킹_어시스트  벌칙_벌칙  \
경기날짜       팀명    결과 이름
2017-10-14 대한항공  0  가스파리니       3       1     0.00    21.43         0      0
                    곽승석         3       0     0.25    11.90         1      0
                    백광현         0       0     0.00     0.00         0      0
                    신영수         0       0     0.00     0.00         0      0
                    정지석         3       0     0.25    14.29         0      0
...                           ...     ...      ...      ...       ...    ...
2022-02-13 현대캐피탈 0  박경민         0       0     0.00     0.00         0      0
                    박상하         4       0     1.00    23.40         1      0
                    전광인         4       0     0.00    17.02         1      0
                    최민호         1       0     0.00     2.13         0      0
                    허수봉         2       0     0.00    10.64         1      0

                           범실_범실     득점점유율  스타팅멤버
경기날짜       팀명    결과 이름
2017-10-14 대한항공  0  가스파리니     11  0.400000      1
                    곽승석        3  0.153846      1
                    백광현        0  0.000000      0
                    신영수        0  0.000000      0
                    정지석        7  0.138462      1
...                          ...       ...    ...
2022-02-13 현대캐피탈 0  박경민        0  0.000000      0
                    박상하        0  0.200000      1
                    전광인        5  0.225000      1
                    최민호        1  0.000000      0
                    허수봉        3  0.450000      1

[11019 rows x 77 columns]

In [31]:
경기별_수치=경기별_수치.reset_index().reset_index()

In [32]:
경기별_수치["홈_어웨이"]=경기별_수치["index"].apply(lambda x : 1 if x%2==0 else 0)
경기별_수치

,index,경기번호,팀명,결과,No.,득점_득점,공격종합_시도,공격종합_성공,공격종합_공격차단,공격종합_범실,...,블로킹_성공,블로킹_유효블락,블로킹_실패,블로킹_범실,블로킹_세트당,블로킹_점유율,블로킹_어시스트,벌칙_벌칙,범실_범실,홈_어웨이
0,0,1,IBK기업은행,0,89,69,179,51,15,10,...,11,37,30,2,2.25,100.01,8,0,25,1
1,1,1,흥국생명,1,127,83,193,63,11,15,...,15,38,12,0,3.30,100.02,10,0,27,0
2,2,2,KGC인삼공사,0,94,79,205,67,20,7,...,7,31,22,2,1.40,99.99,5,0,14,1
3,3,2,현대건설,1,102,102,198,77,7,12,...,20,33,30,3,4.00,100.01,17,0,29,0
4,4,3,GS칼텍스,1,138,88,175,72,9,9,...,7,28,25,0,1.45,100.00,6,0,25,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,943,472,흥국생명,0,111,38,108,32,8,8,...,3,16,18,2,0.99,99.99,3,0,15,0
944,944,473,페퍼저축은행,0,116,44,123,36,10,7,...,4,16,13,0,1.33,100.01,3,0,12,1
945,945,473,한국도로공사,1,124,63,109,49,4,3,...,10,21,19,0,3.33,100.01,9,0,11,0
946,946,474,GS칼텍스,1,164,67,91,52,8,0,...,10,21,17,1,3.34,99.98,8,0,7,1
947,947,474,KGC인삼공사,0,124,45,100,35,10,5,...,8,13,17,0,2.67,99.99,7,0,11,0

In [47]:
home_index = 경기별_수치[경기별_수치['index']/2+1==경기별_수치['경기번호']].index
away_index = 경기별_수치[경기별_수치['index']/2+1!=경기별_수치['경기번호']].index
경기별_수치['상대팀'] = 경기별_수치['팀명']
경기별_수치.loc[home_index,'상대팀']=경기별_수치.loc[away_index,'팀명'].values
경기별_수치.loc[away_index,'상대팀']=경기별_수치.loc[home_index,'팀명'].values
경기별_수치

,index,경기번호,팀명,결과,No.,득점_득점,공격종합_시도,공격종합_성공,공격종합_공격차단,공격종합_범실,...,블로킹_유효블락,블로킹_실패,블로킹_범실,블로킹_세트당,블로킹_점유율,블로킹_어시스트,벌칙_벌칙,범실_범실,홈_어웨이,상대팀
0,0,1,IBK기업은행,0,89,69,179,51,15,10,...,37,30,2,2.25,100.01,8,0,25,1,흥국생명
1,1,1,흥국생명,1,127,83,193,63,11,15,...,38,12,0,3.30,100.02,10,0,27,0,IBK기업은행
2,2,2,KGC인삼공사,0,94,79,205,67,20,7,...,31,22,2,1.40,99.99,5,0,14,1,현대건설
3,3,2,현대건설,1,102,102,198,77,7,12,...,33,30,3,4.00,100.01,17,0,29,0,KGC인삼공사
4,4,3,GS칼텍스,1,138,88,175,72,9,9,...,28,25,0,1.45,100.00,6,0,25,1,한국도로공사
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,943,472,흥국생명,0,111,38,108,32,8,8,...,16,18,2,0.99,99.99,3,0,15,0,IBK기업은행
944,944,473,페퍼저축은행,0,116,44,123,36,10,7,...,16,13,0,1.33,100.01,3,0,12,1,한국도로공사
945,945,473,한국도로공사,1,124,63,109,49,4,3,...,21,19,0,3.33,100.01,9,0,11,0,페퍼저축은행
946,946,474,GS칼텍스,1,164,67,91,52,8,0,...,21,17,1,3.34,99.98,8,0,7,1,KGC인삼공사
947,947,474,KGC인삼공사,0,124,45,100,35,10,5,...,13,17,0,2.67,99.99,7,0,11,0,GS칼텍스

In [48]:
a = ['GS칼텍스', '흥국생명', '한국도로공사', "IBK기업은행", "KGC인삼공사", "현대건설", "페퍼저축은행"]
b=list(range(0,7))
dic = dict(zip(a,b))
dic

{'GS칼텍스': 0,
 '흥국생명': 1,
 '한국도로공사': 2,
 'IBK기업은행': 3,
 'KGC인삼공사': 4,
 '현대건설': 5,
 '페퍼저축은행': 6}

In [49]:
경기별_수치['팀코드']= 경기별_수치['팀명'].replace(dic)
경기별_수치

,index,경기번호,팀명,결과,No.,득점_득점,공격종합_시도,공격종합_성공,공격종합_공격차단,공격종합_범실,...,블로킹_실패,블로킹_범실,블로킹_세트당,블로킹_점유율,블로킹_어시스트,벌칙_벌칙,범실_범실,홈_어웨이,상대팀,팀코드
0,0,1,IBK기업은행,0,89,69,179,51,15,10,...,30,2,2.25,100.01,8,0,25,1,흥국생명,3
1,1,1,흥국생명,1,127,83,193,63,11,15,...,12,0,3.30,100.02,10,0,27,0,IBK기업은행,1
2,2,2,KGC인삼공사,0,94,79,205,67,20,7,...,22,2,1.40,99.99,5,0,14,1,현대건설,4
3,3,2,현대건설,1,102,102,198,77,7,12,...,30,3,4.00,100.01,17,0,29,0,KGC인삼공사,5
4,4,3,GS칼텍스,1,138,88,175,72,9,9,...,25,0,1.45,100.00,6,0,25,1,한국도로공사,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,943,472,흥국생명,0,111,38,108,32,8,8,...,18,2,0.99,99.99,3,0,15,0,IBK기업은행,1
944,944,473,페퍼저축은행,0,116,44,123,36,10,7,...,13,0,1.33,100.01,3,0,12,1,한국도로공사,6
945,945,473,한국도로공사,1,124,63,109,49,4,3,...,19,0,3.33,100.01,9,0,11,0,페퍼저축은행,2
946,946,474,GS칼텍스,1,164,67,91,52,8,0,...,17,1,3.34,99.98,8,0,7,1,KGC인삼공사,0
947,947,474,KGC인삼공사,0,124,45,100,35,10,5,...,17,0,2.67,99.99,7,0,11,0,GS칼텍스,4

In [50]:
경기별_수치.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 948 entries, 0 to 947
Data columns (total 82 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      948 non-null    int64
 1   경기번호       948 non-null    int64
 2   팀명         948 non-null    object
 3   결과         948 non-null    int64
 4   No.        948 non-null    int64
 5   득점_득점      948 non-null    int64
 6   공격종합_시도    948 non-null    int64
 7   공격종합_성공    948 non-null    int64
 8   공격종합_공격차단  948 non-null    int64
 9   공격종합_범실    948 non-null    int64
 10  공격종합_성공률   948 non-null    float64
 11  공격종합_점유율   948 non-null    float64
 12  오픈_시도      948 non-null    int64
 13  오픈_성공      948 non-null    int64
 14  오픈_공격차단    948 non-null    int64
 15  오픈_범실      948 non-null    int64
 16  오픈_성공률     948 non-null    float64
 17  오픈_점유율     948 non-null    float64
 18  시간차_시도     948 non-null    int64
 19  시간차_성공     948 non-null    int64
 20  시간차_공격차단   948 non-null    int64
 21  시간차_범실     948 non-null    int64
 22  시간차_성공률    948 non-null    float64
 23  시간차_점유율    948 non-null    float64
 24  이동_시도      948 non-null    int64
 25  이동_성공      948 non-null    int64
 26  이동_공격차단    948 non-null    int64
 27  이동_범실      948 non-null    int64
 28  이동_성공률     948 non-null    float64
 29  이동_점유율     948 non-null    float64
 30  후위_시도      948 non-null    int64
 31  후위_성공      948 non-null    int64
 32  후위_공격차단    948 non-null    int64
 33  후위_범실      948 non-null    int64
 34  후위_성공률     948 non-null    float64
 35  후위_점유율     948 non-null    float64
 36  속공_시도      948 non-null    int64
 37  속공_성공      948 non-null    int64
 38  속공_공격차단    948 non-null    int64
 39  속공_범실      948 non-null    int64
 40  속공_성공률     948 non-null    float64
 41  속공_점유율     948 non-null    float64
 42  퀵오픈_시도     948 non-null    int64
 43  퀵오픈_성공     948 non-null    int64
 44  퀵오픈_공격차단   948 non-null    int64
 45  퀵오픈_범실     948 non-null    int64
 46  퀵오픈_성공률    948 non-null    float64
 47  퀵오픈_점유율    948 non-null    float64
 48  서브_시도      948 non-null    int64
 49  서브_성공      948 non-null    int64
 50  서브_범실      948 non-null    int64
 51  서브_성공률     948 non-null    float64
 52  서브_점유율     948 non-null    float64
 53  디그_시도      948 non-null    int64
 54  디그_성공      948 non-null    int64
 55  디그_실패      948 non-null    int64
 56  디그_범실      948 non-null    int64
 57  디그_세트당     948 non-null    float64
 58  디그_점유율     948 non-null    float64
 59  세트_시도      948 non-null    int64
 60  세트_성공      948 non-null    int64
 61  세트_범실      948 non-null    int64
 62  세트_세트당     948 non-null    float64
 63  세트_점유율     948 non-null    float64
 64  리시브_시도     948 non-null    int64
 65  리시브_정확     948 non-null    int64
 66  리시브_실패     948 non-null    int64
 67  리시브_세트당    948 non-null    float64
 68  리시브_점유율    948 non-null    float64
 69  블로킹_시도     948 non-null    int64
 70  블로킹_성공     948 non-null    int64
 71  블로킹_유효블락   948 non-null    int64
 72  블로킹_실패     948 non-null    int64
 73  블로킹_범실     948 non-null    int64
 74  블로킹_세트당    948 non-null    float64
 75  블로킹_점유율    948 non-null    float64
 76  블로킹_어시스트   948 non-null    int64
 77  벌칙_벌칙      948 non-null    int64
 78  범실_범실      948 non-null    int64
 79  홈_어웨이      948 non-null    int64
 80  상대팀        948 non-null    object
 81  팀코드        948 non-null    int64
dtypes: float64(24), int64(56), object(2)
memory usage: 607.4+ KB

In [51]:
경기별_수치['공격종합_성공률'] = round(경기별_수치["공격종합_성공"]/경기별_수치['공격종합_시도'], 2)
경기별_수치.drop("공격종합_점유율",axis=1, inplace=True)
경기별_수치['오픈_성공률'] = round(경기별_수치["오픈_성공"]/경기별_수치['오픈_시도'], 2)
경기별_수치.drop("오픈_점유율",axis=1, inplace=True)
경기별_수치['시간차_성공률'] = round(경기별_수치["시간차_성공"]/경기별_수치['시간차_시도'], 2)
경기별_수치.drop("시간차_점유율",axis=1, inplace=True)
경기별_수치['이동_성공률'] = round(경기별_수치["이동_성공"]/경기별_수치['이동_시도'], 2)
경기별_수치.drop("이동_점유율",axis=1, inplace=True)
경기별_수치['후위_성공률'] = round(경기별_수치["후위_성공"]/경기별_수치['후위_시도'], 2)
경기별_수치.drop("후위_점유율",axis=1, inplace=True)
경기별_수치['속공_성공률'] = round(경기별_수치["속공_성공"]/경기별_수치['속공_시도'], 2)
경기별_수치.drop("속공_점유율",axis=1, inplace=True)
경기별_수치['퀵오픈_성공률'] = round(경기별_수치["퀵오픈_성공"]/경기별_수치['퀵오픈_시도'], 2)
경기별_수치.drop("퀵오픈_점유율",axis=1, inplace=True)
경기별_수치['서브_성공률'] = round(경기별_수치["서브_성공"]/경기별_수치['서브_시도'], 2)
경기별_수치.drop("서브_점유율",axis=1, inplace=True)
경기별_수치['디그_성공률'] = round(경기별_수치["디그_성공"]/경기별_수치['디그_시도'], 2)
경기별_수치.drop("디그_점유율",axis=1, inplace=True)
경기별_수치['세트_성공률'] = round(경기별_수치["세트_성공"]/경기별_수치['세트_시도'], 2)
경기별_수치.drop("세트_점유율",axis=1, inplace=True)
경기별_수치['리시브_정확도'] = round(경기별_수치["리시브_정확"]/경기별_수치['리시브_시도'], 2)
경기별_수치.drop("리시브_점유율",axis=1, inplace=True)
경기별_수치['블로킹_성공률'] = round(경기별_수치["블로킹_성공"]/경기별_수치['블로킹_시도'], 2)
경기별_수치.drop("블로킹_점유율",axis=1, inplace=True)
경기별_수치

,index,경기번호,팀명,결과,No.,득점_득점,공격종합_시도,공격종합_성공,공격종합_공격차단,공격종합_범실,...,블로킹_어시스트,벌칙_벌칙,범실_범실,홈_어웨이,상대팀,팀코드,디그_성공률,세트_성공률,리시브_정확도,블로킹_성공률
0,0,1,IBK기업은행,0,89,69,179,51,15,10,...,8,0,25,1,흥국생명,3,0.86,0.27,0.40,0.12
1,1,1,흥국생명,1,127,83,193,63,11,15,...,10,0,27,0,IBK기업은행,1,0.86,0.31,0.51,0.21
2,2,2,KGC인삼공사,0,94,79,205,67,20,7,...,5,0,14,1,현대건설,4,0.81,0.30,0.48,0.09
3,3,2,현대건설,1,102,102,198,77,7,12,...,17,0,29,0,KGC인삼공사,5,0.89,0.36,0.45,0.19
4,4,3,GS칼텍스,1,138,88,175,72,9,9,...,6,0,25,1,한국도로공사,0,0.84,0.38,0.44,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,943,472,흥국생명,0,111,38,108,32,8,8,...,3,0,15,0,IBK기업은행,1,0.81,0.27,0.25,0.06
944,944,473,페퍼저축은행,0,116,44,123,36,10,7,...,3,0,12,1,한국도로공사,6,0.84,0.27,0.37,0.09
945,945,473,한국도로공사,1,124,63,109,49,4,3,...,9,0,11,0,페퍼저축은행,2,0.90,0.43,0.59,0.14
946,946,474,GS칼텍스,1,164,67,91,52,8,0,...,8,0,7,1,KGC인삼공사,0,0.82,0.52,0.48,0.17
947,947,474,KGC인삼공사,0,124,45,100,35,10,5,...,7,0,11,0,GS칼텍스,4,0.72,0.34,0.32,0.18

In [52]:
경기별_수치["범실_범실"]

0      25
1      27
2      14
3      29
4      25
       ..
943    15
944    12
945    11
946     7
947    11
Name: 범실_범실, Length: 948, dtype: int64

In [53]:
경기별_수치.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 948 entries, 0 to 947
Data columns (total 74 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      948 non-null    int64
 1   경기번호       948 non-null    int64
 2   팀명         948 non-null    object
 3   결과         948 non-null    int64
 4   No.        948 non-null    int64
 5   득점_득점      948 non-null    int64
 6   공격종합_시도    948 non-null    int64
 7   공격종합_성공    948 non-null    int64
 8   공격종합_공격차단  948 non-null    int64
 9   공격종합_범실    948 non-null    int64
 10  공격종합_성공률   948 non-null    float64
 11  오픈_시도      948 non-null    int64
 12  오픈_성공      948 non-null    int64
 13  오픈_공격차단    948 non-null    int64
 14  오픈_범실      948 non-null    int64
 15  오픈_성공률     948 non-null    float64
 16  시간차_시도     948 non-null    int64
 17  시간차_성공     948 non-null    int64
 18  시간차_공격차단   948 non-null    int64
 19  시간차_범실     948 non-null    int64
 20  시간차_성공률    920 non-null    float64
 21  이동_시도      948 non-null    int64
 22  이동_성공      948 non-null    int64
 23  이동_공격차단    948 non-null    int64
 24  이동_범실      948 non-null    int64
 25  이동_성공률     764 non-null    float64
 26  후위_시도      948 non-null    int64
 27  후위_성공      948 non-null    int64
 28  후위_공격차단    948 non-null    int64
 29  후위_범실      948 non-null    int64
 30  후위_성공률     948 non-null    float64
 31  속공_시도      948 non-null    int64
 32  속공_성공      948 non-null    int64
 33  속공_공격차단    948 non-null    int64
 34  속공_범실      948 non-null    int64
 35  속공_성공률     945 non-null    float64
 36  퀵오픈_시도     948 non-null    int64
 37  퀵오픈_성공     948 non-null    int64
 38  퀵오픈_공격차단   948 non-null    int64
 39  퀵오픈_범실     948 non-null    int64
 40  퀵오픈_성공률    948 non-null    float64
 41  서브_시도      948 non-null    int64
 42  서브_성공      948 non-null    int64
 43  서브_범실      948 non-null    int64
 44  서브_성공률     948 non-null    float64
 45  디그_시도      948 non-null    int64
 46  디그_성공      948 non-null    int64
 47  디그_실패      948 non-null    int64
 48  디그_범실      948 non-null    int64
 49  디그_세트당     948 non-null    float64
 50  세트_시도      948 non-null    int64
 51  세트_성공      948 non-null    int64
 52  세트_범실      948 non-null    int64
 53  세트_세트당     948 non-null    float64
 54  리시브_시도     948 non-null    int64
 55  리시브_정확     948 non-null    int64
 56  리시브_실패     948 non-null    int64
 57  리시브_세트당    948 non-null    float64
 58  블로킹_시도     948 non-null    int64
 59  블로킹_성공     948 non-null    int64
 60  블로킹_유효블락   948 non-null    int64
 61  블로킹_실패     948 non-null    int64
 62  블로킹_범실     948 non-null    int64
 63  블로킹_세트당    948 non-null    float64
 64  블로킹_어시스트   948 non-null    int64
 65  벌칙_벌칙      948 non-null    int64
 66  범실_범실      948 non-null    int64
 67  홈_어웨이      948 non-null    int64
 68  상대팀        948 non-null    object
 69  팀코드        948 non-null    int64
 70  디그_성공률     948 non-null    float64
 71  세트_성공률     948 non-null    float64
 72  리시브_정확도    948 non-null    float64
 73  블로킹_성공률    948 non-null    float64
dtypes: float64(16), int64(56), object(2)
memory usage: 548.2+ KB

In [54]:
경기별_공격 = 경기별_수치[["경기번호","팀명","결과","공격종합_시도","공격종합_성공"]]
경기별_공격["공격시도중_오픈비율"] = 경기별_수치["오픈_시도"]/경기별_수치["공격종합_시도"]
경기별_공격["공격성공중_오픈비율"] = 경기별_수치["오픈_성공"]/경기별_수치["공격종합_성공"]
경기별_공격["공격시도중_시간차비율"] = 경기별_수치["시간차_시도"]/경기별_수치["공격종합_시도"]
경기별_공격["공격성공중_시간차비율"] = 경기별_수치["시간차_성공"]/경기별_수치["공격종합_성공"]
경기별_공격["공격시도중_이동시율"] = 경기별_수치["이동_시도"]/경기별_수치["공격종합_시도"]
경기별_공격["공격성공중_이동성율"] = 경기별_수치["이동_성공"]/경기별_수치["공격종합_성공"]
경기별_공격["공격시도중_후위시율"] = 경기별_수치["후위_시도"]/경기별_수치["공격종합_시도"]
경기별_공격["공격성공중_후위성율"] = 경기별_수치["후위_성공"]/경기별_수치["공격종합_성공"]
경기별_공격["공격시도중_속공시율"] = 경기별_수치["속공_시도"]/경기별_수치["공격종합_시도"]
경기별_공격["공격성공중_속공성율"] = 경기별_수치["속공_성공"]/경기별_수치["공격종합_성공"]
경기별_공격["공격시도중_퀵오픈비율"] = 경기별_수치["퀵오픈_시도"]/경기별_수치["공격종합_시도"]
경기별_공격["공격성공중_퀵오픈비율"] = 경기별_수치["퀵오픈_성공"]/경기별_수치["공격종합_성공"]
경기별_공격

,경기번호,팀명,결과,공격종합_시도,공격종합_성공,공격시도중_오픈비율,공격성공중_오픈비율,공격시도중_시간차비율,공격성공중_시간차비율,공격시도중_이동시율,공격성공중_이동성율,공격시도중_후위시율,공격성공중_후위성율,공격시도중_속공시율,공격성공중_속공성율,공격시도중_퀵오픈비율,공격성공중_퀵오픈비율
0,1,IBK기업은행,0,179,51,0.491620,0.333333,0.094972,0.176471,0.039106,0.039216,0.117318,0.019608,0.039106,0.019608,0.217877,0.411765
1,1,흥국생명,1,193,63,0.549223,0.428571,0.046632,0.095238,0.046632,0.031746,0.253886,0.333333,0.051813,0.047619,0.051813,0.063492
2,2,KGC인삼공사,0,205,67,0.580488,0.552239,0.019512,0.014925,0.019512,0.014925,0.195122,0.238806,0.029268,0.014925,0.156098,0.164179
3,2,현대건설,1,198,77,0.464646,0.402597,0.141414,0.116883,0.000000,0.000000,0.166667,0.207792,0.080808,0.116883,0.146465,0.155844
4,3,GS칼텍스,1,175,72,0.405714,0.375000,0.040000,0.041667,0.005714,0.000000,0.108571,0.111111,0.142857,0.166667,0.297143,0.305556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,472,흥국생명,0,108,32,0.527778,0.593750,0.018519,0.000000,0.018519,0.000000,0.083333,0.062500,0.111111,0.125000,0.240741,0.218750
944,473,페퍼저축은행,0,123,36,0.731707,0.611111,0.040650,0.083333,0.008130,0.000000,0.073171,0.055556,0.024390,0.000000,0.121951,0.250000
945,473,한국도로공사,1,109,49,0.513761,0.469388,0.064220,0.061224,0.009174,0.020408,0.055046,0.081633,0.055046,0.061224,0.302752,0.306122
946,474,GS칼텍스,1,91,52,0.417582,0.423077,0.010989,0.019231,0.021978,0.038462,0.131868,0.076923,0.098901,0.134615,0.318681,0.307692
947,474,KGC인삼공사,0,100,35,0.420000,0.285714,0.010000,0.000000,0.020000,0.000000,0.180000,0.257143,0.060000,0.085714,0.310000,0.371429

In [55]:
경기별_수치.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 948 entries, 0 to 947
Data columns (total 74 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      948 non-null    int64
 1   경기번호       948 non-null    int64
 2   팀명         948 non-null    object
 3   결과         948 non-null    int64
 4   No.        948 non-null    int64
 5   득점_득점      948 non-null    int64
 6   공격종합_시도    948 non-null    int64
 7   공격종합_성공    948 non-null    int64
 8   공격종합_공격차단  948 non-null    int64
 9   공격종합_범실    948 non-null    int64
 10  공격종합_성공률   948 non-null    float64
 11  오픈_시도      948 non-null    int64
 12  오픈_성공      948 non-null    int64
 13  오픈_공격차단    948 non-null    int64
 14  오픈_범실      948 non-null    int64
 15  오픈_성공률     948 non-null    float64
 16  시간차_시도     948 non-null    int64
 17  시간차_성공     948 non-null    int64
 18  시간차_공격차단   948 non-null    int64
 19  시간차_범실     948 non-null    int64
 20  시간차_성공률    920 non-null    float64
 21  이동_시도      948 non-null    int64
 22  이동_성공      948 non-null    int64
 23  이동_공격차단    948 non-null    int64
 24  이동_범실      948 non-null    int64
 25  이동_성공률     764 non-null    float64
 26  후위_시도      948 non-null    int64
 27  후위_성공      948 non-null    int64
 28  후위_공격차단    948 non-null    int64
 29  후위_범실      948 non-null    int64
 30  후위_성공률     948 non-null    float64
 31  속공_시도      948 non-null    int64
 32  속공_성공      948 non-null    int64
 33  속공_공격차단    948 non-null    int64
 34  속공_범실      948 non-null    int64
 35  속공_성공률     945 non-null    float64
 36  퀵오픈_시도     948 non-null    int64
 37  퀵오픈_성공     948 non-null    int64
 38  퀵오픈_공격차단   948 non-null    int64
 39  퀵오픈_범실     948 non-null    int64
 40  퀵오픈_성공률    948 non-null    float64
 41  서브_시도      948 non-null    int64
 42  서브_성공      948 non-null    int64
 43  서브_범실      948 non-null    int64
 44  서브_성공률     948 non-null    float64
 45  디그_시도      948 non-null    int64
 46  디그_성공      948 non-null    int64
 47  디그_실패      948 non-null    int64
 48  디그_범실      948 non-null    int64
 49  디그_세트당     948 non-null    float64
 50  세트_시도      948 non-null    int64
 51  세트_성공      948 non-null    int64
 52  세트_범실      948 non-null    int64
 53  세트_세트당     948 non-null    float64
 54  리시브_시도     948 non-null    int64
 55  리시브_정확     948 non-null    int64
 56  리시브_실패     948 non-null    int64
 57  리시브_세트당    948 non-null    float64
 58  블로킹_시도     948 non-null    int64
 59  블로킹_성공     948 non-null    int64
 60  블로킹_유효블락   948 non-null    int64
 61  블로킹_실패     948 non-null    int64
 62  블로킹_범실     948 non-null    int64
 63  블로킹_세트당    948 non-null    float64
 64  블로킹_어시스트   948 non-null    int64
 65  벌칙_벌칙      948 non-null    int64
 66  범실_범실      948 non-null    int64
 67  홈_어웨이      948 non-null    int64
 68  상대팀        948 non-null    object
 69  팀코드        948 non-null    int64
 70  디그_성공률     948 non-null    float64
 71  세트_성공률     948 non-null    float64
 72  리시브_정확도    948 non-null    float64
 73  블로킹_성공률    948 non-null    float64
dtypes: float64(16), int64(56), object(2)
memory usage: 548.2+ KB

In [56]:
경기별_공격

,경기번호,팀명,결과,공격종합_시도,공격종합_성공,공격시도중_오픈비율,공격성공중_오픈비율,공격시도중_시간차비율,공격성공중_시간차비율,공격시도중_이동시율,공격성공중_이동성율,공격시도중_후위시율,공격성공중_후위성율,공격시도중_속공시율,공격성공중_속공성율,공격시도중_퀵오픈비율,공격성공중_퀵오픈비율
0,1,IBK기업은행,0,179,51,0.491620,0.333333,0.094972,0.176471,0.039106,0.039216,0.117318,0.019608,0.039106,0.019608,0.217877,0.411765
1,1,흥국생명,1,193,63,0.549223,0.428571,0.046632,0.095238,0.046632,0.031746,0.253886,0.333333,0.051813,0.047619,0.051813,0.063492
2,2,KGC인삼공사,0,205,67,0.580488,0.552239,0.019512,0.014925,0.019512,0.014925,0.195122,0.238806,0.029268,0.014925,0.156098,0.164179
3,2,현대건설,1,198,77,0.464646,0.402597,0.141414,0.116883,0.000000,0.000000,0.166667,0.207792,0.080808,0.116883,0.146465,0.155844
4,3,GS칼텍스,1,175,72,0.405714,0.375000,0.040000,0.041667,0.005714,0.000000,0.108571,0.111111,0.142857,0.166667,0.297143,0.305556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,472,흥국생명,0,108,32,0.527778,0.593750,0.018519,0.000000,0.018519,0.000000,0.083333,0.062500,0.111111,0.125000,0.240741,0.218750
944,473,페퍼저축은행,0,123,36,0.731707,0.611111,0.040650,0.083333,0.008130,0.000000,0.073171,0.055556,0.024390,0.000000,0.121951,0.250000
945,473,한국도로공사,1,109,49,0.513761,0.469388,0.064220,0.061224,0.009174,0.020408,0.055046,0.081633,0.055046,0.061224,0.302752,0.306122
946,474,GS칼텍스,1,91,52,0.417582,0.423077,0.010989,0.019231,0.021978,0.038462,0.131868,0.076923,0.098901,0.134615,0.318681,0.307692
947,474,KGC인삼공사,0,100,35,0.420000,0.285714,0.010000,0.000000,0.020000,0.000000,0.180000,0.257143,0.060000,0.085714,0.310000,0.371429

In [57]:
경기별_수치.groupby("팀명")[["세트_범실"]].mean()

            세트_범실
팀명
GS칼텍스    1.300654
IBK기업은행  1.250000
KGC인삼공사  1.445205
페퍼저축은행   1.333333
한국도로공사   1.006410
현대건설     1.533333
흥국생명     1.095541

In [58]:
# 총 점수 계산 (득점 + 상대팀 범실)

tmp = 경기별_수치.copy()
home_index = 경기별_수치[경기별_수치['index']/2+1==경기별_수치['경기번호']].index
away_index = 경기별_수치[경기별_수치['index']/2+1!=경기별_수치['경기번호']].index
경기별_수치['총_점수'] = 경기별_수치['득점_득점']



경기별_수치.loc[home_index,'총_점수']+=tmp.loc[away_index, "범실_범실"].values
경기별_수치.loc[away_index,'총_점수']+=tmp.loc[home_index, "범실_범실"].values
경기별_수치

,index,경기번호,팀명,결과,No.,득점_득점,공격종합_시도,공격종합_성공,공격종합_공격차단,공격종합_범실,...,벌칙_벌칙,범실_범실,홈_어웨이,상대팀,팀코드,디그_성공률,세트_성공률,리시브_정확도,블로킹_성공률,총_점수
0,0,1,IBK기업은행,0,89,69,179,51,15,10,...,0,25,1,흥국생명,3,0.86,0.27,0.40,0.12,96
1,1,1,흥국생명,1,127,83,193,63,11,15,...,0,27,0,IBK기업은행,1,0.86,0.31,0.51,0.21,108
2,2,2,KGC인삼공사,0,94,79,205,67,20,7,...,0,14,1,현대건설,4,0.81,0.30,0.48,0.09,108
3,3,2,현대건설,1,102,102,198,77,7,12,...,0,29,0,KGC인삼공사,5,0.89,0.36,0.45,0.19,116
4,4,3,GS칼텍스,1,138,88,175,72,9,9,...,0,25,1,한국도로공사,0,0.84,0.38,0.44,0.10,110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,943,472,흥국생명,0,111,38,108,32,8,8,...,0,15,0,IBK기업은행,1,0.81,0.27,0.25,0.06,53
944,944,473,페퍼저축은행,0,116,44,123,36,10,7,...,0,12,1,한국도로공사,6,0.84,0.27,0.37,0.09,55
945,945,473,한국도로공사,1,124,63,109,49,4,3,...,0,11,0,페퍼저축은행,2,0.90,0.43,0.59,0.14,75
946,946,474,GS칼텍스,1,164,67,91,52,8,0,...,0,7,1,KGC인삼공사,0,0.82,0.52,0.48,0.17,78
947,947,474,KGC인삼공사,0,124,45,100,35,10,5,...,0,11,0,GS칼텍스,4,0.72,0.34,0.32,0.18,52

In [60]:
# 실점 컬럼 추가 (본인팀 실점 = 상대팀 총 점수)
home_index = 경기별_수치[경기별_수치['index']/2+1==경기별_수치['경기번호']].index
away_index = 경기별_수치[경기별_수치['index']/2+1!=경기별_수치['경기번호']].index
경기별_수치['실점'] = np.nan

경기별_수치.loc[home_index,'실점']=경기별_수치.loc[away_index, "총_점수"].values
경기별_수치.loc[away_index,'실점']=경기별_수치.loc[home_index, "총_점수"].values
경기별_수치 = 경기별_수치.astype({'실점':"int64"})
경기별_수치

,index,경기번호,팀명,결과,No.,득점_득점,공격종합_시도,공격종합_성공,공격종합_공격차단,공격종합_범실,...,범실_범실,홈_어웨이,상대팀,팀코드,디그_성공률,세트_성공률,리시브_정확도,블로킹_성공률,총_점수,실점
0,0,1,IBK기업은행,0,89,69,179,51,15,10,...,25,1,흥국생명,3,0.86,0.27,0.40,0.12,96,108
1,1,1,흥국생명,1,127,83,193,63,11,15,...,27,0,IBK기업은행,1,0.86,0.31,0.51,0.21,108,96
2,2,2,KGC인삼공사,0,94,79,205,67,20,7,...,14,1,현대건설,4,0.81,0.30,0.48,0.09,108,116
3,3,2,현대건설,1,102,102,198,77,7,12,...,29,0,KGC인삼공사,5,0.89,0.36,0.45,0.19,116,108
4,4,3,GS칼텍스,1,138,88,175,72,9,9,...,25,1,한국도로공사,0,0.84,0.38,0.44,0.10,110,107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,943,472,흥국생명,0,111,38,108,32,8,8,...,15,0,IBK기업은행,1,0.81,0.27,0.25,0.06,53,75
944,944,473,페퍼저축은행,0,116,44,123,36,10,7,...,12,1,한국도로공사,6,0.84,0.27,0.37,0.09,55,75
945,945,473,한국도로공사,1,124,63,109,49,4,3,...,11,0,페퍼저축은행,2,0.90,0.43,0.59,0.14,75,55
946,946,474,GS칼텍스,1,164,67,91,52,8,0,...,7,1,KGC인삼공사,0,0.82,0.52,0.48,0.17,78,52
947,947,474,KGC인삼공사,0,124,45,100,35,10,5,...,11,0,GS칼텍스,4,0.72,0.34,0.32,0.18,52,78

In [61]:
경기별_수치.to_csv('경기별_수치.csv')