In [19]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [20]:
import warnings
import pandas as pd
import numpy as np
warnings.filterwarnings(action='ignore')

In [46]:
import pandas as pd

df = pd.read_csv("남자배구.csv", encoding='utf8')
df.rename(columns={'경기장':'홈_어웨이'},inplace=True)
df.head(10)

,팀명,경기날짜,홈_어웨이,결과,이름,득점_득점,공격종합_시도,공격종합_성공,공격종합_공격차단,공격종합_범실,...,블로킹_실패,블로킹_범실,블로킹_세트당,블로킹_점유율,블로킹_어시스트,벌칙_벌칙,범실_범실,포지션,득점점유율,스타팅멤버
0,현대캐피탈,2017-10-14,1,1,안드레아스,23,34,21,0,1,...,2,1,0.50,25.00,3,0,10,L,0.338235,1
1,현대캐피탈,2017-10-14,1,1,문성민,18,32,17,3,2,...,4,0,0.00,14.58,0,0,7,R,0.264706,1
2,현대캐피탈,2017-10-14,1,1,신영석,10,8,4,1,0,...,4,0,1.25,22.92,2,0,1,C,0.147059,1
3,현대캐피탈,2017-10-14,1,1,김재휘,7,8,4,0,0,...,4,1,0.50,20.83,0,0,5,C,0.102941,1
4,현대캐피탈,2017-10-14,1,1,이시우,7,8,6,0,1,...,1,0,0.00,2.08,1,0,4,L,0.102941,0
5,현대캐피탈,2017-10-14,1,1,박주형,2,4,2,0,0,...,0,0,0.00,0.00,0,0,0,L,0.029412,1
6,현대캐피탈,2017-10-14,1,1,노재욱,1,0,0,0,0,...,2,0,0.25,12.50,1,0,0,S,0.014706,1
7,현대캐피탈,2017-10-14,1,1,여오현,0,0,0,0,0,...,0,0,0.00,0.00,0,0,1,Li,0.000000,0
8,대한항공,2017-10-14,0,0,가스파리니,26,46,24,5,5,...,3,1,0.00,21.43,0,0,11,R,0.400000,1
9,대한항공,2017-10-14,0,0,곽승석,10,16,8,2,0,...,3,0,0.25,11.90,1,0,3,L,0.153846,1

In [47]:
경기별_수치 = df.groupby(["경기날짜", "팀명", "결과"]).sum()
경기별_수치['홈_어웨이'] =np.where(경기별_수치['홈_어웨이']>0,1,0)
경기별_수치

                      홈_어웨이  득점_득점  공격종합_시도  공격종합_성공  공격종합_공격차단  공격종합_범실  \
경기날짜       팀명     결과
2017-10-14 대한항공   0       0     65      105       55         10        8
           현대캐피탈  1       1     68       94       54          4        4
2017-10-15 KB손해보험 1       1     76      116       61         14       11
           삼성화재   0       0     68       90       51          5        6
2017-10-17 OK저축은행 1       1     78      105       57          5       15
...                     ...    ...      ...      ...        ...      ...
2022-02-11 우리카드   0       0     54       80       45          4       11
2022-02-12 KB손해보험 0       0     78      125       65         12        6
           한국전력   1       1     86      123       68          8       10
2022-02-13 OK금융그룹 1       0     51       82       41          6        7
           현대캐피탈  0       1     40       66       33          7        2

                      공격종합_성공률  공격종합_점유율  오픈_시도  오픈_성공  ...  블로킹_유효블락  블로킹_실패  \
경기날짜       팀명     결과                                    ...
2017-10-14 대한항공   0     441.39     94.59     32     15  ...         9      17
           현대캐피탈  1     339.89     96.91     27     13  ...        10      17
2017-10-15 KB손해보험 1     290.96    100.01     40     20  ...        11      26
           삼성화재   0     296.97    100.01     43     19  ...         9      28
2017-10-17 OK저축은행 1     380.92     98.13     40     22  ...        20      20
...                        ...       ...    ...    ...  ...       ...     ...
2022-02-11 우리카드   0     411.19     97.57     40     20  ...         9      25
2022-02-12 KB손해보험 0     325.23    100.00     53     25  ...        17      29
           한국전력   1     389.37    100.01     50     20  ...        20      24
2022-02-13 OK금융그룹 1     350.60     98.78     30     12  ...         8      16
           현대캐피탈  0     226.66     77.64     21      9  ...         9      16

                      블로킹_범실  블로킹_세트당  블로킹_점유율  블로킹_어시스트  벌칙_벌칙  범실_범실  득점점유율  \
경기날짜       팀명     결과
2017-10-14 대한항공   0        1     1.16    97.62         3      0     34    1.0
           현대캐피탈  1        2     2.50    97.91         7      0     28    1.0
2017-10-15 KB손해보험 1        0     1.05    99.99         5      0     35    1.0
           삼성화재   0        2     2.80   100.00        10      0     29    1.0
2017-10-17 OK저축은행 1        1     3.05    92.65        15      0     35    1.0
...                      ...      ...      ...       ...    ...    ...    ...
2022-02-11 우리카드   0        0     1.33    92.30         4      0     29    1.0
2022-02-12 KB손해보험 0        1     1.73    99.99         7      0     19    1.0
           한국전력   1        1     2.40   100.01         9      0     26    1.0
2022-02-13 OK금융그룹 1        0     1.99    92.86         5      0     18    1.0
           현대캐피탈  0        1     1.67    80.85         4      0     13    1.0

                      스타팅멤버
경기날짜       팀명     결과
2017-10-14 대한항공   0       6
           현대캐피탈  1       6
2017-10-15 KB손해보험 1       6
           삼성화재   0       6
2017-10-17 OK저축은행 1       6
...                     ...
2022-02-11 우리카드   0       6
2022-02-12 KB손해보험 0       6
           한국전력   1       6
2022-02-13 OK금융그룹 1       6
           현대캐피탈  0       4

[1220 rows x 77 columns]

In [48]:
경기별_수치=경기별_수치.reset_index().reset_index()
경기별_수치['팀명'].unique()

array(['대한항공', '현대캐피탈', 'KB손해보험', '삼성화재', 'OK저축은행', '한국전력', '우리카드',
       'OK금융그룹'], dtype=object)

In [49]:
a = ['대한항공', '현대캐피탈', 'KB손해보험', '삼성화재', 'OK저축은행', '한국전력', '우리카드','OK금융그룹']
b=list(range(0,8))
dic = dict(zip(a,b))
dic

{'대한항공': 0,
 '현대캐피탈': 1,
 'KB손해보험': 2,
 '삼성화재': 3,
 'OK저축은행': 4,
 '한국전력': 5,
 '우리카드': 6,
 'OK금융그룹': 7}

In [50]:
경기별_수치['팀코드']= 경기별_수치['팀명'].replace(dic)
경기별_수치

,index,경기날짜,팀명,결과,홈_어웨이,득점_득점,공격종합_시도,공격종합_성공,공격종합_공격차단,공격종합_범실,...,블로킹_실패,블로킹_범실,블로킹_세트당,블로킹_점유율,블로킹_어시스트,벌칙_벌칙,범실_범실,득점점유율,스타팅멤버,팀코드
0,0,2017-10-14,대한항공,0,0,65,105,55,10,8,...,17,1,1.16,97.62,3,0,34,1.0,6,0
1,1,2017-10-14,현대캐피탈,1,1,68,94,54,4,4,...,17,2,2.50,97.91,7,0,28,1.0,6,1
2,2,2017-10-15,KB손해보험,1,1,76,116,61,14,11,...,26,0,1.05,99.99,5,0,35,1.0,6,2
3,3,2017-10-15,삼성화재,0,0,68,90,51,5,6,...,28,2,2.80,100.00,10,0,29,1.0,6,3
4,4,2017-10-17,OK저축은행,1,1,78,105,57,5,15,...,20,1,3.05,92.65,15,0,35,1.0,6,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,1215,2022-02-11,우리카드,0,0,54,80,45,4,11,...,25,0,1.33,92.30,4,0,29,1.0,6,6
1216,1216,2022-02-12,KB손해보험,0,0,78,125,65,12,6,...,29,1,1.73,99.99,7,0,19,1.0,6,2
1217,1217,2022-02-12,한국전력,1,1,86,123,68,8,10,...,24,1,2.40,100.01,9,0,26,1.0,6,5
1218,1218,2022-02-13,OK금융그룹,1,0,51,82,41,6,7,...,16,0,1.99,92.86,5,0,18,1.0,6,7
1219,1219,2022-02-13,현대캐피탈,0,1,40,66,33,7,2,...,16,1,1.67,80.85,4,0,13,1.0,4,1

In [51]:
경기별_수치['공격종합_성공률'] = round(경기별_수치["공격종합_성공"]/경기별_수치['공격종합_시도'], 2)
경기별_수치.drop("공격종합_점유율",axis=1, inplace=True)
경기별_수치['오픈_성공률'] = round(경기별_수치["오픈_성공"]/경기별_수치['오픈_시도'], 2)
경기별_수치.drop("오픈_점유율",axis=1, inplace=True)
경기별_수치['시간차_성공률'] = round(경기별_수치["시간차_성공"]/경기별_수치['시간차_시도'], 2)
경기별_수치.drop("시간차_점유율",axis=1, inplace=True)
경기별_수치['이동_성공률'] = round(경기별_수치["이동_성공"]/경기별_수치['이동_시도'], 2)
경기별_수치.drop("이동_점유율",axis=1, inplace=True)
경기별_수치['후위_성공률'] = round(경기별_수치["후위_성공"]/경기별_수치['후위_시도'], 2)
경기별_수치.drop("후위_점유율",axis=1, inplace=True)
경기별_수치['속공_성공률'] = round(경기별_수치["속공_성공"]/경기별_수치['속공_시도'], 2)
경기별_수치.drop("속공_점유율",axis=1, inplace=True)
경기별_수치['퀵오픈_성공률'] = round(경기별_수치["퀵오픈_성공"]/경기별_수치['퀵오픈_시도'], 2)
경기별_수치.drop("퀵오픈_점유율",axis=1, inplace=True)
경기별_수치['서브_성공률'] = round(경기별_수치["서브_성공"]/경기별_수치['서브_시도'], 2)
경기별_수치.drop("서브_점유율",axis=1, inplace=True)
경기별_수치['디그_성공률'] = round(경기별_수치["디그_성공"]/경기별_수치['디그_시도'], 2)
경기별_수치.drop("디그_점유율",axis=1, inplace=True)
경기별_수치['세트_성공률'] = round(경기별_수치["세트_성공"]/경기별_수치['세트_시도'], 2)
경기별_수치.drop("세트_점유율",axis=1, inplace=True)
경기별_수치['리시브_정확도'] = round(경기별_수치["리시브_정확"]/경기별_수치['리시브_시도'], 2)
경기별_수치.drop("리시브_점유율",axis=1, inplace=True)
경기별_수치['블로킹_성공률'] = round(경기별_수치["블로킹_성공"]/경기별_수치['블로킹_시도'], 2)
경기별_수치.drop("블로킹_점유율",axis=1, inplace=True)
경기별_수치['경기번호']=경기별_수치["index"].apply(lambda x : (x//2)+1 if x%2==0 else (x//2)+1)
경기별_수치

,index,경기날짜,팀명,결과,홈_어웨이,득점_득점,공격종합_시도,공격종합_성공,공격종합_공격차단,공격종합_범실,...,벌칙_벌칙,범실_범실,득점점유율,스타팅멤버,팀코드,디그_성공률,세트_성공률,리시브_정확도,블로킹_성공률,경기번호
0,0,2017-10-14,대한항공,0,0,65,105,55,10,8,...,0,34,1.0,6,0,0.72,0.52,0.56,0.10,1
1,1,2017-10-14,현대캐피탈,1,1,68,94,54,4,4,...,0,28,1.0,6,1,0.70,0.51,0.49,0.21,1
2,2,2017-10-15,KB손해보험,1,1,76,116,61,14,11,...,0,35,1.0,6,2,0.80,0.52,0.48,0.10,2
3,3,2017-10-15,삼성화재,0,0,68,90,51,5,6,...,0,29,1.0,6,3,0.69,0.54,0.41,0.22,2
4,4,2017-10-17,OK저축은행,1,1,78,105,57,5,15,...,0,35,1.0,6,4,0.77,0.51,0.52,0.24,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,1215,2022-02-11,우리카드,0,0,54,80,45,4,11,...,0,29,1.0,6,6,0.74,0.52,0.26,0.10,608
1216,1216,2022-02-12,KB손해보험,0,0,78,125,65,12,6,...,0,19,1.0,6,2,0.72,0.51,0.51,0.13,609
1217,1217,2022-02-12,한국전력,1,1,86,123,68,8,10,...,0,26,1.0,6,5,0.67,0.52,0.37,0.19,609
1218,1218,2022-02-13,OK금융그룹,1,0,51,82,41,6,7,...,0,18,1.0,6,7,0.89,0.48,0.46,0.15,610
1219,1219,2022-02-13,현대캐피탈,0,1,40,66,33,7,2,...,0,13,1.0,4,1,0.68,0.50,0.44,0.13,610

In [52]:
경기별_공격 = 경기별_수치[["경기번호",'경기날짜',"팀명","결과","공격종합_시도","공격종합_성공"]]
경기별_공격["공격시도중_오픈비율"] = 경기별_수치["오픈_시도"]/경기별_수치["공격종합_시도"]
경기별_공격["공격성공중_오픈비율"] = 경기별_수치["오픈_성공"]/경기별_수치["공격종합_성공"]
경기별_공격["공격시도중_시간차비율"] = 경기별_수치["시간차_시도"]/경기별_수치["공격종합_시도"]
경기별_공격["공격성공중_시간차비율"] = 경기별_수치["시간차_성공"]/경기별_수치["공격종합_성공"]
경기별_공격["공격시도중_이동시율"] = 경기별_수치["이동_시도"]/경기별_수치["공격종합_시도"]
경기별_공격["공격성공중_이동성율"] = 경기별_수치["이동_성공"]/경기별_수치["공격종합_성공"]
경기별_공격["공격시도중_후위시율"] = 경기별_수치["후위_시도"]/경기별_수치["공격종합_시도"]
경기별_공격["공격성공중_후위성율"] = 경기별_수치["후위_성공"]/경기별_수치["공격종합_성공"]
경기별_공격["공격시도중_속공시율"] = 경기별_수치["속공_시도"]/경기별_수치["공격종합_시도"]
경기별_공격["공격성공중_속공성율"] = 경기별_수치["속공_성공"]/경기별_수치["공격종합_성공"]
경기별_공격["공격시도중_퀵오픈비율"] = 경기별_수치["퀵오픈_시도"]/경기별_수치["공격종합_시도"]
경기별_공격["공격성공중_퀵오픈비율"] = 경기별_수치["퀵오픈_성공"]/경기별_수치["공격종합_성공"]
경기별_공격

,경기번호,경기날짜,팀명,결과,공격종합_시도,공격종합_성공,공격시도중_오픈비율,공격성공중_오픈비율,공격시도중_시간차비율,공격성공중_시간차비율,공격시도중_이동시율,공격성공중_이동성율,공격시도중_후위시율,공격성공중_후위성율,공격시도중_속공시율,공격성공중_속공성율,공격시도중_퀵오픈비율,공격성공중_퀵오픈비율
0,1,2017-10-14,대한항공,0,105,55,0.304762,0.272727,0.028571,0.036364,0.000000,0.0,0.209524,0.218182,0.171429,0.218182,0.285714,0.254545
1,1,2017-10-14,현대캐피탈,1,94,54,0.287234,0.240741,0.053191,0.074074,0.000000,0.0,0.223404,0.222222,0.148936,0.129630,0.287234,0.333333
2,2,2017-10-15,KB손해보험,1,116,61,0.344828,0.327869,0.043103,0.032787,0.000000,0.0,0.293103,0.213115,0.077586,0.098361,0.241379,0.327869
3,2,2017-10-15,삼성화재,0,90,51,0.477778,0.372549,0.011111,0.019608,0.000000,0.0,0.211111,0.294118,0.144444,0.137255,0.155556,0.176471
4,3,2017-10-17,OK저축은행,1,105,57,0.380952,0.385965,0.038095,0.035088,0.019048,0.0,0.238095,0.245614,0.114286,0.140351,0.209524,0.192982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,608,2022-02-11,우리카드,0,80,45,0.500000,0.444444,0.037500,0.044444,0.000000,0.0,0.187500,0.155556,0.150000,0.177778,0.125000,0.177778
1216,609,2022-02-12,KB손해보험,0,125,65,0.424000,0.384615,0.016000,0.015385,0.000000,0.0,0.264000,0.261538,0.128000,0.184615,0.168000,0.153846
1217,609,2022-02-12,한국전력,1,123,68,0.406504,0.294118,0.000000,0.000000,0.000000,0.0,0.235772,0.294118,0.195122,0.220588,0.162602,0.191176
1218,610,2022-02-13,OK금융그룹,1,82,41,0.365854,0.292683,0.012195,0.000000,0.000000,0.0,0.219512,0.268293,0.097561,0.024390,0.304878,0.414634
1219,610,2022-02-13,현대캐피탈,0,66,33,0.318182,0.272727,0.015152,0.030303,0.000000,0.0,0.318182,0.363636,0.106061,0.151515,0.242424,0.181818

In [53]:
남자배구_총득점용= (pd.read_csv('남자배구_시간.csv',encoding='utf8').groupby(['경기번호','팀명']).sum()).reset_index()
남자배구_총득점용['TOTAL']

0       100
1       104
2       106
3       103
4       105
       ...
1215     85
1216    104
1217    106
1218     79
1219     70
Name: TOTAL, Length: 1220, dtype: int64

In [54]:
# 총 점수 계산 (득점 + 상대팀 범실)

# tmp = 경기별_수치.copy()
# home_index = 경기별_수치[경기별_수치['index']/2+1==경기별_수치['경기번호']].index
# away_index = 경기별_수치[경기별_수치['index']/2+1!=경기별_수치['경기번호']].index
경기별_수치['총_점수'] = 남자배구_총득점용['TOTAL']



# 경기별_수치.loc[home_index,'총_점수']+=tmp.loc[away_index, "범실_범실"].values
# 경기별_수치.loc[away_index,'총_점수']+=tmp.loc[home_index, "범실_범실"].values
경기별_수치

,index,경기날짜,팀명,결과,홈_어웨이,득점_득점,공격종합_시도,공격종합_성공,공격종합_공격차단,공격종합_범실,...,범실_범실,득점점유율,스타팅멤버,팀코드,디그_성공률,세트_성공률,리시브_정확도,블로킹_성공률,경기번호,총_점수
0,0,2017-10-14,대한항공,0,0,65,105,55,10,8,...,34,1.0,6,0,0.72,0.52,0.56,0.10,1,100
1,1,2017-10-14,현대캐피탈,1,1,68,94,54,4,4,...,28,1.0,6,1,0.70,0.51,0.49,0.21,1,104
2,2,2017-10-15,KB손해보험,1,1,76,116,61,14,11,...,35,1.0,6,2,0.80,0.52,0.48,0.10,2,106
3,3,2017-10-15,삼성화재,0,0,68,90,51,5,6,...,29,1.0,6,3,0.69,0.54,0.41,0.22,2,103
4,4,2017-10-17,OK저축은행,1,1,78,105,57,5,15,...,35,1.0,6,4,0.77,0.51,0.52,0.24,3,105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,1215,2022-02-11,우리카드,0,0,54,80,45,4,11,...,29,1.0,6,6,0.74,0.52,0.26,0.10,608,85
1216,1216,2022-02-12,KB손해보험,0,0,78,125,65,12,6,...,19,1.0,6,2,0.72,0.51,0.51,0.13,609,104
1217,1217,2022-02-12,한국전력,1,1,86,123,68,8,10,...,26,1.0,6,5,0.67,0.52,0.37,0.19,609,106
1218,1218,2022-02-13,OK금융그룹,1,0,51,82,41,6,7,...,18,1.0,6,7,0.89,0.48,0.46,0.15,610,79
1219,1219,2022-02-13,현대캐피탈,0,1,40,66,33,7,2,...,13,1.0,4,1,0.68,0.50,0.44,0.13,610,70

In [55]:
# 실점 컬럼 추가 (본인팀 실점 = 상대팀 총 점수)
home_index = 경기별_수치[경기별_수치['index']/2+1==경기별_수치['경기번호']].index
away_index = 경기별_수치[경기별_수치['index']/2+1!=경기별_수치['경기번호']].index
경기별_수치['실점'] = np.nan

경기별_수치.loc[home_index,'실점']=경기별_수치.loc[away_index, "총_점수"].values
경기별_수치.loc[away_index,'실점']=경기별_수치.loc[home_index, "총_점수"].values
경기별_수치 = 경기별_수치.astype({'실점':"int64"})
# 여자배구_날짜용 = pd.read_csv('volleyball_raw.csv',encoding='utf8')
# 여자배구_날짜용 = 여자배구_날짜용.groupby(['경기번호','경기날짜','팀명']).sum().reset_index()
# 경기별_수치['경기날짜']=여자배구_날짜용['경기날짜']
경기별_수치 = 경기별_수치.groupby(['경기번호','경기날짜','팀명','홈_어웨이']).sum().reset_index()
경기별_수치.drop(columns='index',inplace=True)

In [75]:
경기별_수치

,경기번호,경기날짜,팀명,홈_어웨이,결과,득점_득점,공격종합_시도,공격종합_성공,공격종합_공격차단,공격종합_범실,...,범실_범실,득점점유율,스타팅멤버,팀코드,디그_성공률,세트_성공률,리시브_정확도,블로킹_성공률,총_점수,실점
0,1,2017-10-14,대한항공,0,0,65,105,55,10,8,...,34,1.0,6,0,0.72,0.52,0.56,0.10,100,104
1,1,2017-10-14,현대캐피탈,1,1,68,94,54,4,4,...,28,1.0,6,1,0.70,0.51,0.49,0.21,104,100
2,2,2017-10-15,KB손해보험,1,1,76,116,61,14,11,...,35,1.0,6,2,0.80,0.52,0.48,0.10,106,103
3,2,2017-10-15,삼성화재,0,0,68,90,51,5,6,...,29,1.0,6,3,0.69,0.54,0.41,0.22,103,106
4,3,2017-10-17,OK저축은행,1,1,78,105,57,5,15,...,35,1.0,6,4,0.77,0.51,0.52,0.24,105,101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,608,2022-02-11,우리카드,0,0,54,80,45,4,11,...,29,1.0,6,6,0.74,0.52,0.26,0.10,85,94
1216,609,2022-02-12,KB손해보험,0,0,78,125,65,12,6,...,19,1.0,6,2,0.72,0.51,0.51,0.13,104,106
1217,609,2022-02-12,한국전력,1,1,86,123,68,8,10,...,26,1.0,6,5,0.67,0.52,0.37,0.19,106,104
1218,610,2022-02-13,OK금융그룹,0,1,51,82,41,6,7,...,18,1.0,6,7,0.89,0.48,0.46,0.15,79,70
1219,610,2022-02-13,현대캐피탈,1,0,40,66,33,7,2,...,13,1.0,4,1,0.68,0.50,0.44,0.13,70,79

In [76]:
경기별_수치.to_csv('남자배구_경기별_수치.csv',index=False)