# 국민건강보험공단_건강검진정보_2021_12 분석
건강검진 결과지 제대로 읽는 법


https://health.chosun.com/site/data/html_dir/2016/11/30/2016113001291.html

# 건강검진정보 csv 병합

In [1]:
url1="https://raw.githubusercontent.com/KimYounghwan/bigdata/master/%EA%B5%AD%EB%AF%BC%EA%B1%B4%EA%B0%95%EB%B3%B4%ED%97%98%EA%B3%B5%EB%8B%A8_%EA%B1%B4%EA%B0%95%EA%B2%80%EC%A7%84%EC%A0%95%EB%B3%B4_20211229_1.CSV"
url2="https://raw.githubusercontent.com/KimYounghwan/bigdata/master/%EA%B5%AD%EB%AF%BC%EA%B1%B4%EA%B0%95%EB%B3%B4%ED%97%98%EA%B3%B5%EB%8B%A8_%EA%B1%B4%EA%B0%95%EA%B2%80%EC%A7%84%EC%A0%95%EB%B3%B4_20211229_2.CSV"
url3="https://raw.githubusercontent.com/KimYounghwan/bigdata/master/%EA%B5%AD%EB%AF%BC%EA%B1%B4%EA%B0%95%EB%B3%B4%ED%97%98%EA%B3%B5%EB%8B%A8_%EA%B1%B4%EA%B0%95%EA%B2%80%EC%A7%84%EC%A0%95%EB%B3%B4_20211229_3.CSV"
url4="https://raw.githubusercontent.com/KimYounghwan/bigdata/master/%EA%B5%AD%EB%AF%BC%EA%B1%B4%EA%B0%95%EB%B3%B4%ED%97%98%EA%B3%B5%EB%8B%A8_%EA%B1%B4%EA%B0%95%EA%B2%80%EC%A7%84%EC%A0%95%EB%B3%B4_20211229_4.CSV"

In [2]:
import pandas as pd

검진정보1=pd.read_csv(url1)
검진정보2=pd.read_csv(url2)
검진정보3=pd.read_csv(url3)
검진정보4=pd.read_csv(url4)

In [3]:
검진정보 = pd.concat([검진정보1,검진정보2,검진정보3,검진정보4,])
검진정보

,기준년도,가입자 일련번호,시도코드,성별코드,연령대 코드(5세단위),신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),...,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마 지티피,흡연상태,음주여부,구강검진 수검여부,치아우식증유무,치석,데이터 공개일자
0,2020,1,36,1,9,165,60,72.1,1.2,1.5,...,1.1,21.0,27.0,21.0,1.0,0.0,0,NaN,NaN,2021-12-29
1,2020,2,27,2,13,150,65,81.0,0.8,0.8,...,0.5,18.0,15.0,15.0,1.0,0.0,0,NaN,NaN,2021-12-29
2,2020,3,11,2,12,155,55,70.0,0.6,0.7,...,0.7,27.0,25.0,7.0,1.0,0.0,0,NaN,NaN,2021-12-29
3,2020,4,31,1,13,160,70,90.8,1.0,1.0,...,1.2,65.0,97.0,72.0,1.0,0.0,1,0.0,0.0,2021-12-29
4,2020,5,41,2,12,155,50,75.2,1.5,1.2,...,0.7,18.0,17.0,14.0,1.0,0.0,0,NaN,NaN,2021-12-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,2020,999996,41,2,13,145,55,81.0,0.9,1.0,...,0.6,21.0,25.0,18.0,1.0,0.0,0,NaN,NaN,2021-12-29
249996,2020,999997,26,2,12,160,55,76.5,1.5,1.5,...,0.8,21.0,14.0,19.0,1.0,1.0,0,NaN,NaN,2021-12-29
249997,2020,999998,48,1,9,175,70,85.0,1.2,1.2,...,0.9,26.0,20.0,17.0,1.0,1.0,0,NaN,NaN,2021-12-29
249998,2020,999999,48,2,9,160,70,91.0,0.6,0.5,...,1.0,25.0,29.0,13.0,1.0,0.0,0,NaN,NaN,2021-12-29
249999,2020,1000000,28,1,11,160,55,76.1,2.0,2.0,...,0.9,17.0,13.0,24.0,2.0,0.0,0,NaN,NaN,2021-12-29

In [4]:
검진정보.columns

Index(['기준년도', '가입자 일련번호', '시도코드', '성별코드', '연령대 코드(5세단위)', '신장(5Cm단위)',
       '체중(5Kg 단위)', '허리둘레', '시력(좌)', '시력(우)', '청력(좌)', '청력(우)', '수축기 혈압',
       '이완기 혈압', '식전혈당(공복혈당)', '총 콜레스테롤', '트리글리세라이드', 'HDL 콜레스테롤', 'LDL 콜레스테롤',
       '혈색소', '요단백', '혈청크레아티닌', '(혈청지오티)AST', '(혈청지오티)ALT', '감마 지티피', '흡연상태',
       '음주여부', '구강검진 수검여부', '치아우식증유무', '치석', '데이터 공개일자'],
      dtype='object')

# 데이터 복사 및 전처리 작업

## 결측값 확인

In [5]:
검진정보.isnull().sum()

기준년도                 0
가입자 일련번호             0
시도코드                 0
성별코드                 0
연령대 코드(5세단위)         0
신장(5Cm단위)            0
체중(5Kg 단위)           0
허리둘레               108
시력(좌)              257
시력(우)              252
청력(좌)              222
청력(우)              230
수축기 혈압            7532
이완기 혈압            7534
식전혈당(공복혈당)        7602
총 콜레스테롤         597694
트리글리세라이드        597678
HDL 콜레스테롤       597685
LDL 콜레스테롤       605529
혈색소               7611
요단백              12141
혈청크레아티닌           7602
(혈청지오티)AST        7601
(혈청지오티)ALT        7602
감마 지티피            7603
흡연상태               343
음주여부               196
구강검진 수검여부            0
치아우식증유무         668617
치석              668618
데이터 공개일자             0
dtype: int64

# 결측치 처리

In [6]:
검진정보['수축기 혈압'] = 검진정보['수축기 혈압'].fillna(검진정보['수축기 혈압'].mean()) 
검진정보['이완기 혈압'] = 검진정보['이완기 혈압'].fillna(검진정보['이완기 혈압'].mean()) 

검진정보['혈색소'] = 검진정보['혈색소'].fillna(검진정보['혈색소'].mean())

검진정보['식전혈당(공복혈당)'] = 검진정보['식전혈당(공복혈당)'].fillna(검진정보['식전혈당(공복혈당)'].mean()) 
검진정보["요단백"] = 검진정보["요단백"].fillna(검진정보["요단백"].mean())
검진정보["혈청크레아티닌"] = 검진정보["혈청크레아티닌"].fillna(검진정보["혈청크레아티닌"].mean())

검진정보['(혈청지오티)AST'] = 검진정보['(혈청지오티)AST'].fillna(검진정보['(혈청지오티)AST'].mode()[0])
검진정보['(혈청지오티)ALT'] = 검진정보['(혈청지오티)ALT'].fillna(검진정보['(혈청지오티)ALT'].mode()[0])

#심장질환 관련 총 콜레스테롤, LDL, HDL, 트리글리세라이드

In [7]:
def 연령대_변환(x):
    x=x['연령대 코드(5세단위)']
    if x==1 or x==2:
        return "10대 이하"
    elif x==3 or x==4:
        return "10대"
    elif x==5 or x==6:
        return "20대"
    elif x==7 or x==8:
        return "30대"
    elif x==9 or x==10:
        return "40대"
    elif x==11 or x==12:
        return "50대"
    elif x==13 or x==14:
        return "60대"
    elif x==15 or x==16:
        return "70대"
    elif x==17 or x==18:
        return "80대"

검진정보["연령대 코드(5세단위)"] = 검진정보.apply(연령대_변환,axis=1)

In [8]:
검진정보.rename(columns={'연령대 코드(5세단위)':'연령대'}, inplace=True)

In [9]:
검진정보["연령대"]

0         40대
1         60대
2         50대
3         60대
4         50대
         ...
249995    60대
249996    50대
249997    40대
249998    40대
249999    50대
Name: 연령대, Length: 1000000, dtype: object

# 성별코드를 성별로 변경

In [10]:
검진정보["성별코드"] = pd.cut(
    검진정보["성별코드"],
    bins=[0,1,2],
    labels="남,여".split(",")
    )

In [11]:
검진정보.rename(columns = {'성별코드' : '성별'}, inplace = True)

In [12]:
검진정보["성별"]

0         남
1         여
2         여
3         남
4         여
         ..
249995    여
249996    여
249997    남
249998    여
249999    남
Name: 성별, Length: 1000000, dtype: category
Categories (2, object): ['남' < '여']

# 시도코드를 시도로 변경

In [13]:
#시도코드 변환
def 시도_변환(x):
    x=x['시도코드']
    if x==11:
        return "서울특별시"
    elif x==26:
        return "부산광역시"
    elif x==27:
        return "대구광역시"
    elif x==28:
        return "인천광역시"
    elif x==29:
        return "광주광역시"
    elif x==30:
        return "대전광역시"
    elif x==31:
        return "울산광역시"
    elif x==36:
        return "세종특별자치시"
    elif x==41:
        return "경기도"
    elif x==42:
        return "강원도"
    elif x==43:
        return "충청북도"
    elif x==44:
        return "충청남도"
    elif x==45:
        return "전라북도"
    elif x==46:
        return "전라남도"
    elif x==47:
        return "경상북도"
    elif x==48:
        return "경상남도"
    elif x==49:
        return "제주특별자치도"


검진정보["시도코드"] = 검진정보.apply(시도_변환,axis=1)

In [14]:
검진정보.rename(columns={"시도코드":"시도"}, inplace=True)

In [15]:
검진정보["시도"]

0         세종특별자치시
1           대구광역시
2           서울특별시
3           울산광역시
4             경기도
           ...
249995        경기도
249996      부산광역시
249997       경상남도
249998       경상남도
249999      인천광역시
Name: 시도, Length: 1000000, dtype: object

# 빈혈유무 구하기

- 혈액이 인체 조직의 대사에 필요한 산소를 충분히 공급하지 못해 조직의 저산소증을 초래하는 경우  
* 구분  
남자 빈혈 : 혈색소 수치 < 13   
여자 빈혈 : 혈색소 수치 < 12

In [16]:
# 빈혈 함수
def 빈혈(x):
    if x['성별'] == '남자':
        if x['혈색소'] < 13:
            return '비정상'
        else:
            return '정상'
    
    else:
        if x['혈색소'] < 12:
            return '비정상'
        else:
            return '정상'

검진정보['빈혈유무'] = 검진정보.apply(빈혈,axis =1)

In [17]:
검진정보['빈혈유무']

0          정상
1          정상
2          정상
3          정상
4          정상
         ...
249995     정상
249996     정상
249997     정상
249998    비정상
249999     정상
Name: 빈혈유무, Length: 1000000, dtype: object

# BMI, 비만도 계산

* BMI 계산 : 체중 / (신장**2*10000)
* 구분  
  (1) 저체중 &nbsp;&nbsp;&nbsp; : BMI < 18.5  
  (2) 정상   &nbsp;&nbsp; &nbsp;&nbsp;   : 18.5 <= BMI < 23.0  
  (3) 위험체중 &nbsp;&nbsp;: 23.0 <= BMI < 25.0  
  (4) 1단계 비만  : 25.0 <= BMI < 30.0  
  (5) 2단계 비만  : BMI > 30.0

In [18]:
#BMI
검진정보["BMI"] = 검진정보["체중(5Kg 단위)"]/검진정보["신장(5Cm단위)"]**2*10000
검진정보["BMI"]=검진정보["BMI"].round(2)

In [20]:
def 비만도_계산(x):
    x=x["BMI"]
    if x<18.5:
        return "저체중"
    elif 18.5<=x<23.0:
        return "정상"
    elif 23.0<=x<25.0:
        return "위험체중"
    elif 25.0<=x<30.0:
        return "1단계 비만"
    elif x>30.0:
        return "2단계 비만"

검진정보["비만정도"] = 검진정보.apply(비만도_계산,axis=1)

In [21]:
검진정보["비만정도"]

0             정상
1         1단계 비만
2             정상
3         1단계 비만
4             정상
           ...
249995    1단계 비만
249996        정상
249997        정상
249998    1단계 비만
249999        정상
Name: 비만정도, Length: 1000000, dtype: object

# 혈압 계산

* 구분  
  (1) 저혈압 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: 수축기 혈압 < 100 & 이완기 혈압 < 60  
  (2) 정상&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   &nbsp; : 수축기 혈압 < 140 & 이완기 혈압 < 90  
  (3) 고혈압  :   수축기 혈압 >= 140 | 이완기 혈압 >= 90

In [22]:
def 혈압(x):
    if (x["수축기 혈압"] < 100) & (x["이완기 혈압"] < 60) :
        return '저혈압'
    elif (x["수축기 혈압"] >= 140) | (x["이완기 혈압"] >= 90):
        return '고혈압'
    else : #(x["수축기 혈압"] < 140) | (x["이완기 혈압"] < 90):
        return '정상혈압'

검진정보["혈압"] = 검진정보.apply(혈압,axis =1)

In [23]:
검진정보["혈압"]

0         정상혈압
1         정상혈압
2         정상혈압
3         정상혈압
4          고혈압
          ...
249995    정상혈압
249996    정상혈압
249997    정상혈압
249998    정상혈압
249999    정상혈압
Name: 혈압, Length: 1000000, dtype: object

# 당뇨병 유무 (공복혈당 계산)

* 구분  
(1) 정상&nbsp;  &nbsp;   &nbsp;&nbsp;&nbsp;&nbsp; : ~ 100 mg/dL  
(2) 공복혈당장애&nbsp; : 100 ~ 125 mg/dL  
(3) 당뇨병&nbsp;   &nbsp;   &nbsp;&nbsp; : 126mg/dL 이상

In [24]:
검진정보["당뇨"] = pd.cut(
    검진정보["식전혈당(공복혈당)"],
    bins=[0,100,125,500],
    labels="정상,공복혈당장애,당뇨병".split(",")
    )

In [25]:
검진정보["당뇨"]

0             정상
1             정상
2         공복혈당장애
3            당뇨병
4         공복혈당장애
           ...
249995    공복혈당장애
249996        정상
249997        정상
249998    공복혈당장애
249999    공복혈당장애
Name: 당뇨, Length: 1000000, dtype: category
Categories (3, object): ['정상' < '공복혈당장애' < '당뇨병']

# 신장질환 유무

1) 요단백
- 소변에 단백질이 나오는 것
- 신장병을 진단하는 중요한 지표 중의 하나
* 구분  
요단백 검사결과 1 : 정상  

2) 크레아티닌
- 화학 물질의 분해로 인해 근육 사용의 천연 부산물
- 운동하는 동안 근육은 크레아틴을 에너지로 전환하여 근육 수축 도움
- 혈중 크레아티닌 수치 증가시 신장질환 위험
- 구분  
성인 남성 : 0.9 ~ 1.3mg  
성인 여성 : 0.6 ~ 1.1mg

In [26]:
# 요단백

def 요단백(x):
        if x['요단백'] == 1:
            return "정상"
        else:
            return "비정상" # 2,3,4,5,6

검진정보["요단백"] = 검진정보.apply(요단백,axis =1)

In [27]:
# 혈청크레아티닌

def 혈청크레아티닌(x):
    if x["성별"] == '남자':
        if (x["혈청크레아티닌"] >= 0.9) & (x["혈청크레아티닌"] <= 1.3):
            return '정상'
        else:
            return '비정상'
    else:
        if (x["혈청크레아티닌"] >= 0.6) & (x["혈청크레아티닌"] <= 1.1):
            return '정상'
        else:
            return '비정상'

검진정보["혈청크레아티닌유무"] = 검진정보.apply(혈청크레아티닌,axis =1)

In [28]:
# 신장질환 함수
def 신장질환(x):
    if x['요단백'] == '정상' :
        if x['혈청크레아티닌유무'] == '비정상' :
            return '위험군'
        else :
            return '정상'
    
    else :
        return '비정상'

검진정보['신장질환'] = 검진정보.apply(신장질환,axis =1)

In [29]:
검진정보['신장질환']

0          정상
1         위험군
2          정상
3         위험군
4          정상
         ...
249995     정상
249996     정상
249997     정상
249998     정상
249999     정상
Name: 신장질환, Length: 1000000, dtype: object

# 간질환 유무

(혈청지오티) GOT(glutamic oxaloacetic transaminase)
- 아미노산을 형성하는 작용
- 건강한 사람의 혈액 중에도 세포에 함유되어 있는 GOT가 소량 유출, 장기의 세포가 파괴되면 대량 흘러나오게 됩니다. 
- 심장, 간, 골격근, 신장, 적혈구에 특히 많이 있는 효소로서 간장애, 심근경색, 용혈 등을 진단하는데 유용

In [30]:
def 간질환_계산(x):
    if (x['(혈청지오티)AST']<=40.0) & (x['(혈청지오티)ALT']<=40.0):
        return "정상"
    elif (x['(혈청지오티)AST']<=40.0) & (x['(혈청지오티)ALT']>40.0) :
        return "위험군"
    elif (x['(혈청지오티)AST']>40.0) & (x['(혈청지오티)ALT']<=40.0):
        return "위험군"
    elif (x['(혈청지오티)AST']>40.0) & (x['(혈청지오티)ALT']>40.0):
        return "비정상"

검진정보["간질환"] = 검진정보.apply(간질환_계산,axis=1)

In [31]:
검진정보["간질환"]

0          정상
1          정상
2          정상
3         비정상
4          정상
         ...
249995     정상
249996     정상
249997     정상
249998     정상
249999     정상
Name: 간질환, Length: 1000000, dtype: object

# 심장질환 유무

1) 콜레스테롤  
- 세포막을 구성하는 주요성분의 하나이며 세포의 기능에 필수적인 물질  
- 비정상적으로 많아지면 다른 지방물질과 함께 혈관내벽에 쌓여 혈관이 좁아짐  
- 혈관수축이 원활하지 못하게 되어 동맥경화를 비롯한 각종 혈관계 질환 발병 가능성 큼

#### 총콜레스테롤 
   * 총 콜레스테롤 수치가 정상이어도 HDL, LDL, 트리글리세라이드가 비정상인 경우가 있다.
#### HDL
   * 40이하 비정상
#### LDL
   * 130 이하 정상
   * 130~ 비정상
#### 트리글리세라이드
   * 150미만 정상
   * 150이상 비정상

In [32]:
심장질환 = (검진정보[검진정보['LDL 콜레스테롤'].notnull()])
심장질환.dropna(axis=0, subset=['총 콜레스테롤'],inplace=True)
심장질환.reset_index(drop=True,inplace=True)

C:\Users\onegt\AppData\Local\Temp\ipykernel_12864\2275548561.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  심장질환.dropna(axis=0, subset=['총 콜레스테롤'],inplace=True)

In [33]:
def 심장질환_계산(x):
    if (x['HDL 콜레스테롤']>40.0) & (x['LDL 콜레스테롤']<=130) & (x['트리글리세라이드']<150):
        return "정상"
    elif (x['HDL 콜레스테롤']<=40.0) & (x['LDL 콜레스테롤']<=130) & (x['트리글리세라이드']<150):
        return "HDL"
    elif (x['HDL 콜레스테롤']>40.0) & (x['LDL 콜레스테롤']>130) & (x['트리글리세라이드']<150):
        return "LDL"
    elif (x['HDL 콜레스테롤']>40.0) & (x['LDL 콜레스테롤']<=130) & (x['트리글리세라이드']>=150):
        return "트리글리"
    elif (x['HDL 콜레스테롤']<=40.0) & (x['LDL 콜레스테롤']<=130) & (x['트리글리세라이드']>=150):
        return "HDL,트리글리"
    elif (x['HDL 콜레스테롤']>40.0) & (x['LDL 콜레스테롤']>130) & (x['트리글리세라이드']>=150):
        return "LDL,트리글리"
    elif (x['HDL 콜레스테롤']<=40.0) & (x['LDL 콜레스테롤']>130) & (x['트리글리세라이드']<150):
        return "HDL,LDL"
    elif (x['HDL 콜레스테롤']<=40.0) & (x['LDL 콜레스테롤']>130) & (x['트리글리세라이드']>=150):
        return "HDL,LDL,트리글리"
심장질환["심장질환"] = 심장질환.apply(심장질환_계산,axis=1)

C:\Users\onegt\AppData\Local\Temp\ipykernel_12864\1029559382.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  심장질환["심장질환"] = 심장질환.apply(심장질환_계산,axis=1)

In [34]:
심장질환

,기준년도,가입자 일련번호,시도,성별,연령대,신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),...,데이터 공개일자,빈혈유무,BMI,비만정도,혈압,당뇨,혈청크레아티닌유무,신장질환,간질환,심장질환
0,2020,1,세종특별자치시,남,40대,165,60,72.1,1.2,1.5,...,2021-12-29,정상,22.04,정상,정상혈압,정상,정상,정상,정상,정상
1,2020,5,경기도,여,50대,155,50,75.2,1.5,1.2,...,2021-12-29,정상,20.81,정상,고혈압,공복혈당장애,정상,정상,정상,"LDL,트리글리"
2,2020,6,대구광역시,남,40대,185,85,94.0,1.2,1.2,...,2021-12-29,정상,24.84,위험체중,정상혈압,정상,정상,정상,정상,"LDL,트리글리"
3,2020,7,충청남도,남,40대,165,80,93.0,0.8,0.7,...,2021-12-29,정상,29.38,1단계 비만,정상혈압,당뇨병,정상,정상,정상,"HDL,트리글리"
4,2020,9,경기도,여,80대,150,50,82.0,0.4,0.5,...,2021-12-29,정상,22.22,정상,정상혈압,공복혈당장애,정상,정상,비정상,정상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394452,2020,999993,대전광역시,남,60대,175,90,99.5,0.9,0.9,...,2021-12-29,정상,29.39,1단계 비만,정상혈압,정상,정상,정상,비정상,HDL
394453,2020,999996,경기도,여,60대,145,55,81.0,0.9,1.0,...,2021-12-29,정상,26.16,1단계 비만,정상혈압,공복혈당장애,정상,정상,정상,트리글리
394454,2020,999997,부산광역시,여,50대,160,55,76.5,1.5,1.5,...,2021-12-29,정상,21.48,정상,정상혈압,정상,정상,정상,정상,LDL
394455,2020,999999,경상남도,여,40대,160,70,91.0,0.6,0.5,...,2021-12-29,비정상,27.34,1단계 비만,정상혈압,공복혈당장애,정상,정상,정상,정상
394456,2020,1000000,인천광역시,남,50대,160,55,76.1,2.0,2.0,...,2021-12-29,정상,21.48,정상,정상혈압,공복혈당장애,정상,정상,정상,LDL

## 데이터 전처리 완료된 DF -> csv로 저장

In [35]:
검진정보

,기준년도,가입자 일련번호,시도,성별,연령대,신장(5Cm단위),체중(5Kg 단위),허리둘레,시력(좌),시력(우),...,치석,데이터 공개일자,빈혈유무,BMI,비만정도,혈압,당뇨,혈청크레아티닌유무,신장질환,간질환
0,2020,1,세종특별자치시,남,40대,165,60,72.1,1.2,1.5,...,NaN,2021-12-29,정상,22.04,정상,정상혈압,정상,정상,정상,정상
1,2020,2,대구광역시,여,60대,150,65,81.0,0.8,0.8,...,NaN,2021-12-29,정상,28.89,1단계 비만,정상혈압,정상,비정상,위험군,정상
2,2020,3,서울특별시,여,50대,155,55,70.0,0.6,0.7,...,NaN,2021-12-29,정상,22.89,정상,정상혈압,공복혈당장애,정상,정상,정상
3,2020,4,울산광역시,남,60대,160,70,90.8,1.0,1.0,...,0.0,2021-12-29,정상,27.34,1단계 비만,정상혈압,당뇨병,비정상,위험군,비정상
4,2020,5,경기도,여,50대,155,50,75.2,1.5,1.2,...,NaN,2021-12-29,정상,20.81,정상,고혈압,공복혈당장애,정상,정상,정상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,2020,999996,경기도,여,60대,145,55,81.0,0.9,1.0,...,NaN,2021-12-29,정상,26.16,1단계 비만,정상혈압,공복혈당장애,정상,정상,정상
249996,2020,999997,부산광역시,여,50대,160,55,76.5,1.5,1.5,...,NaN,2021-12-29,정상,21.48,정상,정상혈압,정상,정상,정상,정상
249997,2020,999998,경상남도,남,40대,175,70,85.0,1.2,1.2,...,NaN,2021-12-29,정상,22.86,정상,정상혈압,정상,정상,정상,정상
249998,2020,999999,경상남도,여,40대,160,70,91.0,0.6,0.5,...,NaN,2021-12-29,비정상,27.34,1단계 비만,정상혈압,공복혈당장애,정상,정상,정상
249999,2020,1000000,인천광역시,남,50대,160,55,76.1,2.0,2.0,...,NaN,2021-12-29,정상,21.48,정상,정상혈압,공복혈당장애,정상,정상,정상

In [36]:
검진정보.to_csv("검진정보.csv", index=False)

In [37]:
심장질환.to_csv("심장질환.csv", index=False)